/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreflightRouteImport } from './routes/preflight'
import { Route as ApiEvaluateRouteImport } from './routes/api/evaluate'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreflightRoute = PreflightRouteImport.update({
  id: '/preflight',
  path: '/preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preflight': typeof PreflightRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preflight': typeof PreflightRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preflight': typeof PreflightRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preflight' | '/api/evaluate' | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preflight' | '/api/evaluate' | '/api/public/health'
  id: '__root__' | '/' | '/preflight' | '/api/evaluate' | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreflightRoute: typeof PreflightRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preflight': {
      id: '/preflight'
      path: '/preflight'
      fullPath: '/preflight'
      preLoaderRoute: typeof PreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreflightRoute: PreflightRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
