/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreflightRouteImport } from './routes/preflight'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ApiEvaluateRouteImport } from './routes/api/evaluate'
import { Route as ApiVerifyRouteImport } from './routes/api/verify'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreflightRoute = PreflightRouteImport.update({
  id: '/preflight',
  path: '/preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRoute = ApiVerifyRouteImport.update({
  id: '/api/verify',
  path: '/api/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preflight': typeof PreflightRoute
  '/review': typeof ReviewRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/verify': typeof ApiVerifyRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preflight': typeof PreflightRoute
  '/review': typeof ReviewRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/verify': typeof ApiVerifyRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preflight': typeof PreflightRoute
  '/review': typeof ReviewRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/verify': typeof ApiVerifyRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preflight'
    | '/review'
    | '/api/evaluate'
    | '/api/verify'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preflight'
    | '/review'
    | '/api/evaluate'
    | '/api/verify'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/preflight'
    | '/review'
    | '/api/evaluate'
    | '/api/verify'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreflightRoute: typeof PreflightRoute
  ReviewRoute: typeof ReviewRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
  ApiVerifyRoute: typeof ApiVerifyRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preflight': {
      id: '/preflight'
      path: '/preflight'
      fullPath: '/preflight'
      preLoaderRoute: typeof PreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify': {
      id: '/api/verify'
      path: '/api/verify'
      fullPath: '/api/verify'
      preLoaderRoute: typeof ApiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreflightRoute: PreflightRoute,
  ReviewRoute: ReviewRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
  ApiVerifyRoute: ApiVerifyRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
